[workspace]
authors = ["iury Simoes-Sousa <iuryt@pm.me>"]
channels = ["conda-forge"]
name = "vortex_profile_matching"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[feature.legacy39.dependencies]
_ipython_minor_entry_point = { version = "==8.7.0" }
adal = { version = "==1.2.7" }
adlfs = { version = "==2023.1.0" }
affine = { version = "==2.4.0" }
aiobotocore = { version = "==2.12.2" }
aiofiles = { version = "==23.1.0" }
aioitertools = { version = "==0.11.0" }
aiosignal = { version = "==1.3.1" }
anyio = { version = "==4.3.0" }
appdirs = { version = "==1.4.4" }
argon2-cffi = { version = "==23.1.0" }
arrow = { version = "==1.3.0" }
asciitree = { version = "==0.3.3" }
asttokens = { version = "==2.2.1" }
async-timeout = { version = "==4.0.2" }
attrs = { version = "==22.2.0" }
babel = { version = "==2.14.0" }
backcall = { version = "==0.2.0" }
backports = { version = "==1.0" }
"backports.functools_lru_cache" = { version = "==1.6.4" }
beautifulsoup4 = { version = "==4.11.2" }
bleach = { version = "==6.0.0" }
blinker = { version = "==1.5" }
bokeh = { version = "==2.4.3" }
boto3 = { version = "==1.34.51" }
botocore = { version = "==1.34.51" }
bottleneck = { version = "==1.3.5" }
bounded-pool-executor = { version = "==0.0.3" }
bqplot = { version = "==0.12.43" }
branca = { version = "==0.6.0" }
bzip2 = { version = "==1.0.8" }
cairo = { version = "==1.16.0" }
cartopy = { version = "==0.23.0" }
certifi = { version = "==2024.8.30" }
cf_xarray = { version = "==0.9.1" }
cffi = { version = "==1.15.1" }
cftime = { version = "==1.6.2" }
cgen = { version = "==2020.1" }
charset-normalizer = { version = "==2.1.1" }
click = { version = "==8.1.3" }
click-plugins = { version = "==1.1.1" }
cligj = { version = "==0.7.2" }
cloudpickle = { version = "==2.2.0" }
cmasher = { version = "==1.8.0" }
cmcrameri = { version = "==1.7" }
cmocean = { version = "==2.0" }
colorama = { version = "==0.4.6" }
colorcet = { version = "==3.0.1" }
colorspacious = { version = "==1.1.2" }
colour = { version = "==0.1.5" }
comm = { version = "==0.1.2" }
contourpy = { version = "==1.0.6" }
copernicusmarine = { version = "==1.2.0" }
cryptography = { version = "==38.0.4" }
curl = { version = "==7.87.0" }
cycler = { version = "==0.11.0" }
cytoolz = { version = "==0.12.0" }
dask = { version = "==2022.12.1" }
dask-core = { version = "==2022.12.1" }
dask-glm = { version = "==0.2.0" }
dask-jobqueue = { version = "==0.8.1" }
dask-ml = { version = "==2023.3.24" }
dataclasses = { version = "==0.8" }
datashader = { version = "==0.14.4" }
datashape = { version = "==0.5.4" }
dateparser = { version = "==1.1.8" }
dcw-gmt = { version = "==2.2.0" }
debugpy = { version = "==1.6.4" }
decorator = { version = "==5.1.1" }
defusedxml = { version = "==0.7.1" }
distributed = { version = "==2022.12.1" }
dnspython = { version = "==2.6.1" }
docopt = { version = "==0.6.2" }
docrep = { version = "==0.3.2" }
earthaccess = { version = "==0.9.0" }
earthengine-api = { version = "==0.1.408" }
ee_extra = { version = "==0.0.15" }
eerepr = { version = "==0.0.4" }
entrypoints = { version = "==0.4" }
erddapy = { version = "==1.2.1" }
esmf = { version = "==8.4.1" }
et_xmlfile = { version = "==1.1.0" }
exceptiongroup = { version = "==1.1.1" }
fasteners = { version = "==0.17.3" }
fastparquet = { version = "==2023.8.0" }
ffmpeg = { version = "==5.1.2" }
ffmpeg-python = { version = "==0.2.0" }
fftw = { version = "==3.3.10" }
filelock = { version = "==3.12.2" }
fiona = { version = "==1.9.1" }
flox = { version = "==0.6.8" }
folium = { version = "==0.14.0" }
font-ttf-dejavu-sans-mono = { version = "==2.37" }
font-ttf-inconsolata = { version = "==3.0" }
font-ttf-source-code-pro = { version = "==2.38" }
font-ttf-ubuntu = { version = "==0.83" }
fonts-conda-ecosystem = { version = "==1" }
fonts-conda-forge = { version = "==1" }
fqdn = { version = "==1.5.1" }
freexl = { version = "==1.0.6" }
fribidi = { version = "==1.0.10" }
frozenlist = { version = "==1.3.3" }
fsspec = { version = "==2023.12.2" }
ftfy = { version = "==6.1.1" }
future = { version = "==0.18.3" }
gdal = { version = "==3.6.2" }
gdk-pixbuf = { version = "==2.42.10" }
gdown = { version = "==5.2.0" }
geeadd = { version = "==0.5.6" }
geemap = { version = "==0.32.1" }
geocoder = { version = "==1.38.1" }
geojson = { version = "==3.1.0" }
geopandas = { version = "==0.12.2" }
geopandas-base = { version = "==0.12.2" }
geos = { version = "==3.11.1" }
geotiff = { version = "==1.7.1" }
geoviews = { version = "==1.9.6" }
geoviews-core = { version = "==1.9.6" }
gettext = { version = "==0.21.1" }
gflags = { version = "==2.2.2" }
ghostscript = { version = "==10.4.0" }
giflib = { version = "==5.2.1" }
glib = { version = "==2.74.1" }
glib-tools = { version = "==2.74.1" }
glog = { version = "==0.6.0" }
gmpy2 = { version = "==2.1.2" }
gmt = { version = "==6.4.0" }
google-api-core = { version = "==2.19.1" }
google-api-python-client = { version = "==2.135.0" }
google-auth = { version = "==2.30.0" }
google-auth-httplib2 = { version = "==0.2.0" }
google-cloud-core = { version = "==2.4.1" }
google-cloud-storage = { version = "==2.17.0" }
google-crc32c = { version = "==1.1.2" }
google-resumable-media = { version = "==2.7.0" }
googleapis-common-protos = { version = "==1.63.2" }
graphite2 = { version = "==1.3.13" }
graphviz = { version = "==7.1.0" }
grpcio = { version = "==1.51.1" }
gshhg-gmt = { version = "==2.3.7" }
gsl = { version = "==2.7" }
gsw = { version = "==3.4.0" }
gts = { version = "==0.7.6" }
h11 = { version = "==0.14.0" }
h2 = { version = "==4.1.0" }
h5netcdf = ">=1.6.4,<2"
h5py = { version = "==3.7.0" }
harfbuzz = { version = "==6.0.0" }
hdf4 = { version = "==4.2.15" }
hdf5 = { version = "==1.12.2" }
heapdict = { version = "==1.0.1" }
holoviews = { version = "==1.15.4" }
hpack = { version = "==4.0.0" }
httpcore = { version = "==1.0.5" }
httplib2 = { version = "==0.22.0" }
hvplot = { version = "==0.10.0" }
hyperframe = { version = "==6.0.1" }
icu = { version = "==70.1" }
idna = { version = "==3.4" }
importlib-metadata = { version = "==6.1.0" }
importlib_resources = { version = "==5.12.0" }
iniconfig = { version = "==2.0.0" }
intake = { version = "==0.7.0" }
intake-parquet = { version = "==0.3.0" }
intake-xarray = { version = "==0.7.0" }
ipycytoscape = { version = "==1.3.3" }
ipyevents = { version = "==2.0.2" }
ipyfilechooser = { version = "==0.6.0" }
ipykernel = { version = "==6.19.4" }
ipyleaflet = { version = "==0.18.2" }
ipython = { version = "==8.7.0" }
ipython_genutils = { version = "==0.2.0" }
ipytree = { version = "==0.2.2" }
ipywidgets = { version = "==8.0.4" }
isodate = { version = "==0.6.1" }
isoduration = { version = "==20.11.0" }
jedi = { version = "==0.18.2" }
jinja2 = { version = "==3.1.2" }
jmespath = { version = "==1.0.1" }
joblib = { version = "==1.2.0" }
jpeg = { version = "==9e" }
json-c = { version = "==0.16" }
json5 = { version = "==0.9.25" }
jsonpointer = { version = "==3.0.0" }
jsonschema = { version = "==4.17.3" }
jsonschema-with-format-nongpl = { version = "==4.17.3" }
jupyter_client = { version = "==7.4.8" }
jupyter_core = { version = "==5.1.1" }
jupyter_events = { version = "==0.6.3" }
jupyter_server = { version = "==2.10.0" }
jupyter_server_terminals = { version = "==0.5.3" }
jupyterlab = { version = "==3.5.3" }
jupyterlab_pygments = { version = "==0.3.0" }
jupyterlab_server = { version = "==2.24.0" }
jupyterlab_widgets = { version = "==3.0.5" }
kealib = { version = "==1.5.0" }
kiwisolver = { version = "==1.4.4" }
lame = { version = "==3.100" }
lcms2 = { version = "==2.14" }
lerc = { version = "==4.0.0" }
libnetcdf = { version = "==4.9.1" }
libogg = { version = "==1.3.4" }
libopenblas = { version = "==0.3.21" }
libopus = { version = "==1.3.1" }
libpng = { version = "==1.6.39" }
libpq = { version = "==15.2" }
libprotobuf = { version = "==3.21.12" }
librsvg = { version = "==2.54.4" }
librttopo = { version = "==1.1.0" }
libsndfile = { version = "==1.1.0" }
libsodium = { version = "==1.0.18" }
lxml = { version = "==4.9.2" }
lz4 = { version = "==4.2.0" }
lz4-c = { version = "==1.9.3" }
mailchecker = { version = "==4.1.19" }
mapclassify = { version = "==2.5.0" }
markdown = { version = "==3.4.3" }
markupsafe = { version = "==2.1.1" }
matplotlib = { version = "==3.6.2" }
matplotlib-base = { version = "==3.6.2" }
matplotlib-inline = { version = "==0.1.6" }
mistune = { version = "==3.0.2" }
motuclient = { version = "==1.8.8" }
mpc = { version = "==1.3.1" }
mpfr = { version = "==4.2.0" }
mpg123 = { version = "==1.31.1" }
mpmath = { version = "==1.3.0" }
msal = { version = "==1.21.0" }
msal_extensions = { version = "==1.0.0" }
msgpack-python = { version = "==1.0.4" }
msrest = { version = "==0.7.1" }
multidict = { version = "==6.0.4" }
multimethod = { version = "==1.9.1" }
multipledispatch = { version = "==0.6.0" }
munch = { version = "==2.5.0" }
munkres = { version = "==1.1.4" }
mysql-common = { version = "==8.0.31" }
mysql-libs = { version = "==8.0.31" }
nbclassic = { version = "==1.1.0" }
nbclient = { version = "==0.10.0" }
nbconvert-core = { version = "==7.16.4" }
nbformat = { version = "==5.7.3" }
nco = { version = "==5.1.5" }
nest-asyncio = { version = "==1.6.0" }
netcdf-fortran = { version = "==4.6.0" }
netcdf4 = { version = "==1.6.3" }
networkx = { version = "==3.0" }
nodejs = { version = "==18.15.0" }
notebook = { version = "==6.5.7" }
notebook-shim = { version = "==0.2.4" }
numba = { version = "==0.56.4" }
numcodecs = { version = "==0.11.0" }
numpy = { version = "==1.23.5" }
numpy_groupies = { version = "==0.9.20" }
oauthlib = { version = "==3.2.2" }
odc-geo = { version = "==0.3.3" }
odc-stac = { version = "==0.3.5" }
openh264 = { version = "==2.3.1" }
openjpeg = { version = "==2.5.0" }
openpyxl = { version = "==3.1.1" }
openssl = { version = "==3.1.7" }
orc = { version = "==1.8.2" }
osmnx = { version = "==1.9.3" }
overrides = { version = "==7.7.0" }
owslib = { version = "==0.29.2" }
packaging = { version = "==22.0" }
pandas = { version = "==1.5.2" }
pandocfilters = { version = "==1.5.0" }
panel = { version = "==0.14.4" }
pango = { version = "==1.50.12" }
param = { version = "==1.13.0" }
parquet-cpp = { version = "==1.5.1" }
parso = { version = "==0.8.3" }
partd = { version = "==1.3.0" }
pcre = { version = "==8.45" }
pcre2 = { version = "==10.40" }
pexpect = { version = "==4.8.0" }
phonenumbers = { version = "==8.13.7" }
pickleshare = { version = "==0.7.5" }
pillow = { version = "==9.2.0" }
pip = { version = "==22.3.1" }
pixman = { version = "==0.40.0" }
pkgutil-resolve-name = { version = "==1.3.10" }
planetary-computer = { version = "==0.4.9" }
platformdirs = { version = "==2.6.2" }
plotly = { version = "==5.17.0" }
pluggy = { version = "==1.0.0" }
ply = { version = "==3.11" }
pooch = { version = "==1.7.0" }
poppler = { version = "==23.1.0" }
poppler-data = { version = "==0.4.12" }
portalocker = { version = "==2.7.0" }
postgresql = { version = "==15.2" }
pqdm = { version = "==0.1.0" }
proj = { version = "==9.1.1" }
prometheus_client = { version = "==0.20.0" }
prompt-toolkit = { version = "==3.0.36" }
proto-plus = { version = "==1.23.0" }
protobuf = { version = "==4.21.12" }
psutil = { version = "==5.9.4" }
pthread-stubs = { version = "==0.4" }
ptyprocess = { version = "==0.7.0" }
pure_eval = { version = "==0.2.2" }
pyarrow = { version = "==11.0.0" }
pyasn1 = { version = "==0.6.0" }
pyasn1-modules = { version = "==0.4.0" }
pycparser = { version = "==2.21" }
pycrs = { version = "==1.0.2" }
pyct = { version = "==0.4.6" }
pyct-core = { version = "==0.4.6" }
pydantic = { version = "==1.10.7" }
pydap = { version = "==3.3.0" }
pygments = { version = "==2.13.0" }
pygmt = { version = "==0.11.0" }
pyjwt = { version = "==2.6.0" }
pymbolic = { version = "==2022.2" }
pymongo = { version = "==4.6.3" }
pyopenssl = { version = "==22.1.0" }
pyparsing = { version = "==3.0.9" }
pyperclip = { version = "==1.8.2" }
pyproj = { version = "==3.4.1" }
pyrsistent = { version = "==0.19.3" }
pyshp = { version = "==2.3.1" }
pysocks = { version = "==1.7.1" }
pystac = { version = "==1.10.0" }
pystac-client = { version = "==0.6.1" }
pytest = { version = "==7.3.1" }
python = { version = "==3.9.15" }
python-benedict = { version = "==0.26.0" }
python-box = { version = "==7.2.0" }
python-cmr = { version = "==0.11.0" }
python-dateutil = { version = "==2.8.2" }
python-fastjsonschema = { version = "==2.16.3" }
python-fsutil = { version = "==0.10.0" }
python-json-logger = { version = "==2.0.7" }
python-slugify = { version = "==6.1.2" }
python_abi = { version = "==3.9" }
pytools = { version = "==2022.1.14" }
pytz = { version = "==2022.7" }
pyu2f = { version = "==0.1.5" }
pyviz_comms = { version = "==2.2.1" }
pyyaml = { version = "==6.0" }
pyzmq = { version = "==24.0.1" }
rasterio = { version = "==1.3.6" }
ratelim = { version = "==0.1.6" }
re2 = { version = "==2023.2.1" }
regex = { version = "==2023.6.3" }
requests = { version = "==2.28.1" }
requests-oauthlib = { version = "==1.3.1" }
retrying = { version = "==1.3.3" }
rfc3339-validator = { version = "==0.1.4" }
rfc3986-validator = { version = "==0.1.1" }
roaring-landmask = { version = "==0.7.1" }
rsa = { version = "==4.9" }
rtree = { version = "==1.0.1" }
"ruamel.yaml" = { version = "==0.18.6" }
"ruamel.yaml.clib" = { version = "==0.2.8" }
s3fs = { version = "==2023.12.2" }
s3transfer = { version = "==0.10.1" }
sankee = { version = "==0.2.5" }
scipy = { version = "==1.9.3" }
scooby = { version = "==0.10.0" }
seawater = { version = "==3.3.4" }
semver = { version = "==3.0.2" }
send2trash = { version = "==1.8.3" }
setuptools = { version = "==69.5.1" }
sip = { version = "==6.7.5" }
six = { version = "==1.16.0" }
sleef = { version = "==3.5.1" }
snappy = { version = "==1.1.10" }
sniffio = { version = "==1.3.1" }
snuggs = { version = "==1.4.7" }
sortedcontainers = { version = "==2.4.0" }
soupsieve = { version = "==2.3.2.post1" }
spatialpandas = { version = "==0.4.9" }
spectate = { version = "==1.0.1" }
sqlite = { version = "==3.40.0" }
stack_data = { version = "==0.6.2" }
streamz = { version = "==0.6.4" }
svt-av1 = { version = "==1.4.1" }
sympy = { version = "==1.12" }
tbb = { version = "==2021.9.0" }
tblib = { version = "==1.7.0" }
tenacity = { version = "==8.2.3" }
terminado = { version = "==0.18.1" }
text-unidecode = { version = "==1.3" }
threadpoolctl = { version = "==3.1.0" }
tiledb = { version = "==2.13.2" }
tinycss2 = { version = "==1.3.0" }
tinynetrc = { version = "==1.3.1" }
tk = { version = "==8.6.12" }
toml = { version = "==0.10.2" }
tomli = { version = "==2.0.1" }
toolz = { version = "==0.12.0" }
tornado = { version = "==6.2" }
tqdm = { version = "==4.66.2" }
traitlets = { version = "==5.8.0" }
traittypes = { version = "==0.2.1" }
trajan = { version = "==0.3.3" }
types-python-dateutil = { version = "==2.9.0.20240316" }
typing-extensions = { version = "==4.11.0" }
typing_extensions = { version = "==4.11.0" }
typing_utils = { version = "==0.1.0" }
tzdata = { version = "==2022g" }
tzlocal = { version = "==5.0.1" }
udunits2 = { version = "==2.2.28" }
unicodedata2 = { version = "==15.0.0" }
unidecode = { version = "==1.3.6" }
uri-template = { version = "==1.3.0" }
uritemplate = { version = "==4.1.1" }
urllib3 = { version = "==1.26.13" }
watchdog = { version = "==4.0.0" }
wcwidth = { version = "==0.2.5" }
webcolors = { version = "==24.6.0" }
webencodings = { version = "==0.5.1" }
webob = { version = "==1.8.7" }
websocket-client = { version = "==1.8.0" }
wheel = { version = "==0.38.4" }
whitebox = { version = "==2.3.4" }
whiteboxgui = { version = "==2.3.0" }
widgetsnbextension = { version = "==4.0.5" }
wrapt = { version = "==1.14.1" }
x264 = { version = "==1!164.3095" }
x265 = { version = "==3.5" }
xarray = { version = "==2024.3.0" }
xerces-c = { version = "==3.2.4" }
xhistogram = ">=0.3.2,<0.4"
xlrd = { version = "==2.0.1" }
xmltodict = { version = "==0.13.0" }
xorg-fixesproto = { version = "==5.0" }
xorg-kbproto = { version = "==1.0.7" }
xorg-libice = { version = "==1.0.10" }
xorg-libsm = { version = "==1.2.3" }
xorg-libx11 = { version = "==1.8.4" }
xorg-libxau = { version = "==1.0.9" }
xorg-libxdmcp = { version = "==1.1.3" }
xorg-libxext = { version = "==1.3.4" }
xorg-libxfixes = { version = "==5.0.3" }
xorg-libxrender = { version = "==0.9.10" }
xorg-renderproto = { version = "==0.11.1" }
xorg-xextproto = { version = "==7.3.0" }
xorg-xproto = { version = "==7.0.31" }
xrft = { version = "==1.0.1" }
xyzservices = { version = "==2023.2.0" }
xz = { version = "==5.2.6" }
yaml = { version = "==0.2.5" }
yarl = { version = "==1.8.2" }
zarr = { version = "==2.14.2" }
zeromq = { version = "==4.3.4" }
zict = { version = "==2.2.0" }
zipp = { version = "==3.15.0" }
zlib = { version = "==1.2.13" }
zstd = { version = "==1.5.2" }

[pypi-dependencies]
mixsea = "==0.1.1"
shapely = "==2.0.1"
wget = "==3.2"

[feature.aws.dependencies]
python = "3.11.*"
icechunk = ">=1.1.3,<2"
xarray = ">=2025.8.0,<2026"
zarr = ">=3.1.1,<4"
s3fs = ">=2025.7.0,<2026"
boto3 = ">=1.39.11,<2"
ipykernel = ">=6.30.1,<7"
awscli = ">=2.28.16,<3"

[environments]
default = ["legacy39"]
aws = ["aws"]
